### PR TITLE
Mic functionality added for the main page search bar

### PR DESCRIPTION
**Pull request by raashika03**
https://user-images.githubusercontent.com/45493793/113645857-4a954980-96a5-11eb-910b-d4ddc4ebde84.mp4

I added mic functionality, so that for people with disabilities there won't be problem (no need to type) and it also saves time. On pressing on mic icon a pop-up appears which asks for the access(like in zoom or other apps). For creating the video and testing the functionality locally, I was needed to forcefully off that setting because chrome wasn't letting me test (because it was saying it's insecure, because of localhost :face_with_head_bandage: ) ). So, I disabled it.
@matuskalas @hmenager have a look :smile: I tried to do like google chrome.

### CODE REVIEW

**Comment by bryan-brancotte** [comment]
Hi @raashika03 

Thanks for you enthousiasme, but I will decline this PR:
 * I am not sure that this functionality is needed.
 * When considering scientific term, abbreviation (RNASeq), and accent of each person I am not confident in the ability of the speech to text to help user save time (while definitely consuming network).
 * (Part) of this code can be found in multiple website, I don't know the source neither the license 
   * https://bl.ocks.org/kzkamiya/453f38bd3abf9a4f2568
   * https://coderoad.ru/49698515/python-flask-socketio-%D0%BD%D0%B5-%D0%B2%D1%8B%D0%B7%D1%8B%D0%B2%D0%B0%D0%B5%D1%82-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%BE%D0%B5-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5-%D0%B8%D0%B7-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0-JS

When re-using work done by other one must always indicate the sources, and when submitting this code to existing project, one should always check what is the license.

**Comment by raashika03** [comment]
Thank a lot @bryan-brancotte I understood well your point.
FYI- used this as the source code https://github.com/Daniel-Hug/speech-input

**Comment by bryan-brancotte** [comment]
Thanks for providing the source, FYI it is an MIT licence which allows you to do almost everything with this code.

**Comment by raashika03** [comment]
> 
> * I am not sure that this functionality is needed.

what about this case? it can catch and search for anything not only for abbreviations.
Screenshot from 2021-04-09 21-47-36
>
> * When considering scientific term, abbreviation (RNASeq), and accent of each person I am not confident in the ability of the speech to text to help user save time (while definitely consuming network).

Is there any scope of improvement. what else I can do?
@bryan-brancotte How can I check if it can catch for all accents?

**Pull request closed without merging**
