### PR TITLE
Search icon position

### LINKED ISSUE #102: Overflow of search bar in smart phones
When we don't use search bar, scrolling is possible to the term details table

Screenshot_2021-04-10-14-57-00-01

When we use search bar, it's not possible to go down without scrolling in a single flow(taking care to not scroll inside the image) 

Screenshot_2021-04-10-14-58-26-44

Few other websites search bar with no overflow condition

Screenshot_2021-04-10-15-00-59-80

Screenshot_2021-04-10-15-02-17-08

So should I try changing Edam search bar similarly? To prevent this problem. @bryan-brancotte @matuskalas @hmenager

### PR DESCRIPTION
**Pull request by raashika03**
### Checklist

- [X] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [X] I only changed lines related to my PR (no bulk reformatting)
- [X] I indicated the source and check the license if I re-use code, or I did not re-use code
- [X] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue 

close #102 this issue will be closed with [this commit](https://github.com/edamontology/edam-browser/commit/1f22191c7e83669f2070a489a569007e08322c5a) and this PR.

### Details
Before:
IMG_20210504_155334

After:
Screenshot from 2021-05-04 15-17-21

### CODE REVIEW

**Comment by bryan-brancotte** [comment]
Hi @raashika03 I forgot to close #102 when adding viewport, done

**Comment by raashika03** [comment]
Ok @bryan-brancotte review this if it's needed.

**Comment by raashika03** [comment]
or search icon could also be removed like [logo removal here](https://github.com/edamontology/edam-browser/commit/8da0b2a22d4bd9bc8e81004e198d36c4776c18e4)

**Comment by bryan-brancotte** [comment]
Your PR fixes :+1:  the overlapping issue of placeholder going over/under the magnifying glass, but I kind of like the fact that the magnifying glass is still visible when entering text. To do so I would have simple used  `.search-term{padding-right: 2em;}` but if you have any more concise solution (like the  other here, but with the magnifying glass all the time) do not hesitate.

P.S: After some reading it seems that the glass should be even more [visible](https://www.nngroup.com/articles/magnifying-glass-icon/)

**Comment by raashika03** [comment]
Ok give me some time to think and try the best approach :)

**Pull request closed without merging**
