### PR TITLE
Displaying relevant term relationship in create new term form

### LINKED ISSUE #50: Display term relationships which are relevant in term creation form
### Edit:

`Is Identifier Of` does not exist yet, and should be created, the others have been done in #174

### Original post

The relationships showed in the form should be only the ones for the type of concept considered.
Here's a table of which relationship should be showed, depending on the type of concept the user suggests.
(Please not `Is Identifier Of` does not exist yet, and should be created).

|relationship|applicable to| status |
|---------------|-----------------| ----- |
|Parent|all| nothing to do |
|Has Topic|Operation, Data| done |
|Is Format Of|Format| done |
|Has Input|Operation| done |
|Has Output|Operation| done |
|Is Identifier Of|Identifier| to do |

### PR DESCRIPTION
**Pull request by pooja2299**
### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] I only changed lines related to my PR (no bulk reformating)
- [ ] I indicated the source and check the license if I re-use code, or I did not re-use code
- [ ] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue

resolve #50

### CODE REVIEW

**Comment by pooja2299** [comment]
I have solved issue #50. But I messed up with my local repository, so extra files also got committed . For now I am keeping this commit for reference and will do required fixes later on.

**Comment by bryan-brancotte** [comment]
Hi @pooja2299 please follow the checklist, and in particular that no bulk reformatting is done (and I think there is some in the PR)

**Comment by pooja2299** [comment]
I have created another PR #168 for resolving issue #50 . @bryan-brancotte should this PR be closed or should i revert this commit?

**Comment by raashika03** [comment]
since another PR covers the same issue with same content so ideally this can be closed. @pooja2299

**Comment by pooja2299** [comment]
> since another PR covers the same issue with same content so ideally this can be closed. @pooja2299

yes, I was also thinking the same. @bryan-brancotte should i close it?

**Pull request closed without merging**
