### PR TITLE
#176 Added 'Is Identifier Of' term relationship in the edit form

### LINKED ISSUE #176: Add 'Is Identifier Of' term relationship in term relation form
`Is Identifier Of` term relationship to be added as mentioned in issue #50 .

### PR DESCRIPTION
**Pull request by pooja2299**
### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformatting)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue

resolve #176

### CODE REVIEW

**Comment by pooja2299** [comment]
Hi @bryan-brancotte. I added the `Is Identifier Of` field in the edit form. But need help in 'hide' and 'show' of this term because the `s_branch` would give "data" as branch name in identifier term:

image

**Comment by bryan-brancotte** [comment]
Hi @pooja2299 

Indentifier is not a branch, but a sub-branch, of data. I searched the code and AFAIK there is not function to test if an element is an ancestor of another. You thus have to write your own (I can push it if you want). Then you will add `optional_rel` `identifier_rel` css class to the new block you added, and do the show as previously done. For any of that I can push some code if you want, do not hesitate to ask.

**Comment by pooja2299** [comment]
> Hi @pooja2299
> 
> Indentifier is not a branch, but a sub-branch, of data. I searched the code and AFAIK there is not function to test if an element is an ancestor of another. You thus have to write your own (I can push it if you want). Then you will add `optional_rel` `identifier_rel` css class to the new block you added, and do the show as previously done. For any of that I can push some code if you want, do not hesitate to ask.

Thanks for your suggestion! I will surely try. Currently I am going through my end semester examinations. Will update this after my exams.

**Review by bryan-brancotte — APPROVED** [review]
Hi @pooja2299 Thanks for you work in this PR, and not only. I added the final code that was needed to complet the PR. Now merging :)

**Pull request merged**
