### PR TITLE
#135 Changed mouse pointer when hovered over node text .

### PR DESCRIPTION
**Pull request by pooja2299**

### CODE REVIEW

**Comment by pooja2299** [comment]
In the local run section of README file the command to run was given `start_edam_stand_alone_browser.sh` . But I think giving complete command would be useful : `./start_edam_stand_alone_browser.sh'.  Also provided the bullet points to the steps to follow.

**Comment by raashika03** [comment]
IMG_20210422_174442
Mentioned in contribution.md :)

**Comment by pooja2299** [comment]
Thanks @raashika03 . I tried creating different PR but it came inside my previous PR . It would be great if you can help me in this.

**Comment by raashika03** [comment]
Create another branch from your main branch or  any other branch, then make changes for your 2nd issue in that branch and then you can create another pr for this readme one separately. 

And revert the readme changes in the main branch since you're pushing from your main branch for this mouse pointer issue. Then this pr will contain changes for pointer issue only.

**Comment by pooja2299** [comment]
Ok thanks!

**Comment by raashika03** [comment]
#85 #97 @pooja2299 I think you should check the comments once. Regarding reformatting.

**Comment by bryan-brancotte** [comment]
Hi @pooja2299 

Thanks for making me discover `pointer-events: none;` #125 and this PR both solved the issue, but #125 was older so I merged the otherone. Anyway thanks for the contribution !

**Pull request closed without merging**
