### PR TITLE
update README.md with platform-specific start instructions

### PR DESCRIPTION
**Pull request by sunny775**
Hi @bryan-brancotte  @hmenager .
This pull request adds the changes suggested in issue #123  , to give a more straight forward approach to running EDAM browser locally

### CODE REVIEW

**Comment by matuskalas** [comment]
I think this is useful 👍🏽

But what about the `start_edam_stand_alone_browser.sh` option? I like that one too. Or is it now going to be obsolete?

On Windows, it might often be needed to run `sh start_edam_stand_alone_browser.sh` instead. And `python3.exe` then has to exists, for example as a symbolic link.

I think it's great to mention the VS option as an alternative, but I'd suggest there should also be a documented option without VS.

**Comment by sunny775** [comment]
Thanks @matuskalas for the review. I'll include the options and commit them them right away

**Comment by sunny775** [comment]
Hi @matuskalas . Check the changes I've made if they are ok.  I've included python3 as a separate option since that would easily work on any platform with python3 installed.
Also check the changes I proposed in pull #121 to enable the use of `yarn start` or `npm start`

**Comment by bryan-brancotte** [comment]
Hi @sunny775 I resolved some conflict in order to merge it now as it is needed by #122

**Comment by sunny775** [comment]
Alright. Thanks @bryan-brancotte

**Comment by bryan-brancotte** [comment]
thanks to you @sunny775

**Pull request merged**
