### PR TITLE
ehance the home page design

### PR DESCRIPTION
**Pull request by tawahpeggy**
I am currently working on improving the ui design and experience of the edam- browser's home page

### CODE REVIEW

**Comment by raashika03** [comment]
Hi @tawahpeggy it'll be nice if you can provide some description of the changes you made at least in the form of some images. It let other people see what you changed without trying out the code locally.

**Comment by tawahpeggy** [comment]
Thanks @raashika03

**Comment by tawahpeggy** [comment]
changed the proposed logo 
Screenshot from 2021-04-26 06-56-04

**Comment by bryan-brancotte** [comment]
Hi, @tawahpeggy 
I have the feeling that after #143 this PR might be not relevante anymore. I am thus closing it. Feel free to continu the work while starting from the latest version in a new PR.
Best wishes

**Pull request closed without merging**
