### PR TITLE
Enhancing the UI of details section!

### PR DESCRIPTION
**Pull request by secrashi**
Before: 

before

After: 

WhatsApp Image 2021-04-09 at 11 30 20 PM

### CODE REVIEW

**Comment by bryan-brancotte** [comment]
Hi @secrashi 

It's a good start, to continue solving this issue, here are some questions that could help you:
 * Is breaking word the normal behavior ?
 * if not why was it set, and also how ?
 * Could this work be done without adding code, but removing some instead ?

**Comment by secrashi** [comment]
Hi @bryan-brancotte, 

1. Breaking of words into characters isn't normal behavior.
2. It was set by assigning the word-break property of CSS to break-all!
3. It can be solved by editing the word-break prop of CSS from break-all to break-word. Just Removing the code wouldn't be enough since by default that property will be set to normal, which will make the content flow out of the box as shown in the image attached below: 
WhatsApp Image 2021-04-10 at 2 42 07 PM

Though to write a more organized code, we can add the word-break property where it appears first without mentioning the class again. I guess I should have done this in the first place but I missed it somehow. Should I close this and make another PR for it?

**Review by bryan-brancotte — CHANGES_REQUESTED** [review]
Hi @secrashi 

Good analysis. In such situation it is preferable to edit current css code than adding news code that always overrule current css. It make the code more readable and reduce chance of misinterpreting while reading it.
Nevertheless you are in the good direction with `break-word`

**Comment by secrashi** [comment]
I totally agree, @bryan-brancotte. Thanks for letting me know. I'll make the required changes soon!

**Comment by secrashi** [comment]
Hey @bryan-brancotte, I have made the required changes! Please have a look.

**Comment by bryan-brancotte** [comment]
:clap: well done

**Pull request merged**
