### PR TITLE
prevent selection when dragging and resizing tree

### LINKED ISSUE #200: unwanted Text selection on vertical extension of tree box using resizer
Screenshot from 2021-05-22 23-51-56

### PR DESCRIPTION
**Pull request by bryan-brancotte**
Closes #200

### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformatting)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue

Closes #200

### Details

I am wondering if the selectability of text is used somewhere, but I don't think so.

### CODE REVIEW

**Comment by raashika03** [comment]
@bryan-brancotte selectability of text is used only inside tooltip in the svg & that's not getting affected. So, this's ok to merge.

**Comment by bryan-brancotte** [comment]
You are right @raashika03 but the selection glitch also appears ni the tree-controls, I thus prevent selection in them when not pointing in them.

**Comment by raashika03** [comment]
Or [this](https://github.com/edamontology/edam-browser/issues/200#issuecomment-846640266) can be used as a better solution. 
so that even previously seen term or any other element is not selected.

**Comment by raashika03** [comment]
Screenshot from 2021-05-25 19-17-00
After using resizer, after enabling tooltip for the normal screen.

**Comment by raashika03** [comment]
Thus needs to look for some other approach. Removing text selection for all the elements might be a tedious task this way ig.

**Comment by raashika03** [comment]
Now, this's all good. Cross-checked done, for all glitches.

**Review by HagerDakroury — APPROVED** [review]
tested and looks good! Ready to merge 👍

**Comment by bryan-brancotte** [comment]
You can thus squash and merge :)

**Comment by HagerDakroury** [comment]
> 
> 
> You can thus squash and merge :)

I can't. Looks like I'm not an authorized user.

**Pull request merged**
