### PR TITLE
[WIP]Tree box border effect

### LINKED ISSUE #69: Adding visual effect for tree map box
adding a resize feature in the tree map box will be a good idea I think, cause while scrolling through the browser in smaller screens like in phone, tree map box acquires almost the whole screen leaving some spaces below and above it, and only those spaces can be used for scrolling which makes it difficult for the user to scroll down or up.
IMG_20210401_173607
Only red area marked can be used for scrolling down, which seems frustrating, I felt this when I used Edam browser in the phone for the first time, 
I thought my phone isn't working :( took me few minutes to realise that box isn't scrollable like other elements. Even scrolling using vertical scrollbar isn't at all feasible in phone at least because of its less width by default.
 

So a decrease option to minimise the box size( not to zero)  will be nice.

1) It can be done something similar to what's there for applications in an os, Resizing using cursor at the corners. 
images

2) Another way can be to provide a button kind of thing like in some PDF reader to change size to 50%, 100%, 10%... For the tree map box only. 
IMG_20210401_174557

I think 1 will work in desktop version only, so option 2 can be used which will be made to appear for screens of size less than a particular value. 

Refreshing is also difficult currently.

What are your views @bryan-brancotte @matuskalas @hmenager :-)

### PR DESCRIPTION
**Pull request by raashika03**
resolve #69 
Has the same effect as #95 for devices with mouse.

### CODE REVIEW

**Comment by raashika03** [comment]
```
$("document").ready(function () {
    $("#tree-and-controls").mousemove(function () {
        $(this).addClass("tree-border");
    }).mouseleave(function () {
        $(this).removeClass("tree-border");
    });
});

```
event listeners works sound when I use mousemove/ mouseleave (checked on laptop) but it doesn't work when I use touchmove/ touchstart/ touchend (I checked on touch screen, my phone) @bryan-brancotte what can be the reason. I'm stuck. I scorched almost every thing but couldn't understand the reason for the same. 

```
$("document").ready(function () {
    $("#tree-and-controls").touchstart(function () {
        $(this).addClass("tree-border");
    }).touchend(function () {
        $(this).removeClass("tree-border");
    });
});

```
This's all we need for displaying border in touchscreen devices.

**Comment by raashika03** [comment]
So, I'm thinking that I'll do for devices with mouse as like I did in #95, then for touchscreens I'll handle separately using event listeners.
CSS is faster in terms of performance so this approach sounds better. @bryan-brancotte your views please.

**Comment by raashika03** [comment]
Screenshot from 2021-04-15 12-40-30
I checked like this @bryan-brancotte so it should work. other changes were reflecting like I tried #95 on this then it was working properly.
Screenshot from 2021-04-15 12-46-54

**Comment by raashika03** [comment]
@bryan-brancotte can you leave any comment on this. I'm waiting for review :)

**Comment by bryan-brancotte** [comment]
I did not get that there was a question.

I recommend you that you enable github pages for the branch tree-border of your fork (https://github.com/raashika03/edam-browser/tree/tree-border) so you will be able to actually test it on smartphone as it is the main goal of issue #69

**Comment by raashika03** [comment]
Ok @bryan-brancotte thank you

**Pull request closed without merging**
