### PR TITLE
some might be useful options

### PR DESCRIPTION
**Pull request by raashika03**
Screenshot from 2021-03-31 02-46-50
[Back to top] directs to the top of the page (useful for smaller screens)
Edit this page directs the user to the [Contribution Guide](https://github.com/edamontology/edam-browser/blob/main/CONTRIBUTING.md) if one is willing to contribute.

I added edit this page, because it's no where mentioned on how to contribute (assuming that they don't know about the source repository), if a person who doesn't have so sound knowledge of all the terms used in the browser but still wants to suggest some feature than this might be useful.
Suppose, that person doesn't want to add something like [this](https://edamontology.github.io/edam-browser/edit.html?term=http://edamontology.org/data_2914&branch=data) then they might use it to suggest some bug or other features, or even they can contact the maintainer by this.

### CODE REVIEW

**Comment by raashika03** [comment]
@bryan-brancotte would you like to make any comment on this. If it's a good thing or not. So that I can either close this or can be merged.

**Comment by matuskalas** [comment]
Hi @raashika03 and @bryan-brancotte, we dicussed this with @hmenager today too and we like it (partly related to your #62), and he will write you further instructions soon 😉

**Review by hmenager — CHANGES_REQUESTED** [review]
Thank you for this proposition! The "back to top" option can prove very useful, esp. with e.g. smartphone screens. However, I wouldn't keep the "Edit this page" button, that kind of functionality is super helpful for people familiar with GitHub, but here some will not be. So, this option could be confused for an option to request changes in EDAM ontology itself, which it is not (we have the `[+] ` and `[edit] ` buttons for that. So, can you **keep `back to top`**, and **remove `edit this page`**?

**Comment by raashika03** [comment]
Done @hmenager :)

**Review by hmenager — APPROVED** [review]

**Pull request merged**
