### PR TITLE
Grabbing cursor for the tree map

### LINKED ISSUE #105: Propose changing the mouse cursor to a hand when moving the tree around
@matuskalas @hmenager @bryan-brancotte It could be useful to have a hand cursor icon when interacting with the tree instead of the mouse cursor to alert the user that they're able to pull and push the tree around. When hovering over the nodes on the tree, a pointer cursor appears, but outside of that there is only the mouse cursor. 

Would having a hand/grabbing cursor be more helpful instead?

### PR DESCRIPTION
**Pull request by raashika03**
### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformatting)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue

close #105

PR:
close #129 

### Details

https://user-images.githubusercontent.com/45493793/117392791-6d1eba80-af10-11eb-958e-eaf833703f98.mp4

### CODE REVIEW

**Review by bryan-brancotte — CHANGES_REQUESTED** [review]
Hi

This does not solve  #105 as the pointer is always in grabbing state, not only when *grabbing* and moving the tree around

**Comment by raashika03** [comment]
No please review it closely. It's in pointer state when nodes are clickable. In rest other condition it's in grabbing state.

**Comment by bryan-brancotte** [comment]
> In rest other condition(where grabbing/moving the tree is possible) it's in grabbing state.

I agree with you, the cursor grabbing is the one use by default. It is used even when not grabbing the tree and that is a UX issue.

Solving #105 will also solve #69, and reciprocally as both want to provide a feedback to the user and (s)he is moving the tree.

**Comment by raashika03** [comment]
> 
> It is used even when not grabbing the tree and that is a UX issue.

can you show me the area where this's happening. I see wherever grabbing cursor is present grabbing is possible there and  we can move the tree map using that location.

Do you mean that grabbing should appear only when cursor is on the tree map.
outside tree map it should be default one. then at the nodes pointer will be there.

But grabbing is working even outside tree map. 
@bryan-brancotte please clarify.

**Comment by raashika03** [comment]
grabbing is possible for the whole svg. Ok this you mean by UX issue.

So, this issue should have grabbing cursor only on the tree?

**Pull request closed without merging**
